name: Update files.json

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate files.json
        run: |
          echo '{"files": [' > files.json
          find uploads -type f | sed 's/^/{"path": "&"},/' >> files.json
          sed -i '$ s/,$//' files.json
          echo ']}' >> files.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add files.json
          git diff --staged --quiet || (git commit -m "Auto-update files.json" && git push)
